name: KMM Bridge Publish Release
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  kmmbridgepublish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.7
